import json
import unittest
from starp.parsers import XmlParser

class TestPairwiseParser(unittest.TestCase):

    xml = """<?xml version="1.0"?>
<!DOCTYPE BlastOutput PUBLIC "-//NCBI//NCBI BlastOutput/EN" "http://www.ncbi.nlm.nih.gov/dtd/NCBI_BlastOutput.dtd">
<BlastOutput>
  <BlastOutput_program>blastn</BlastOutput_program>
  <BlastOutput_version>BLASTN 2.2.28+</BlastOutput_version>
  <BlastOutput_reference>Stephen F. Altschul, Thomas L. Madden, Alejandro A. Sch&amp;auml;ffer, Jinghui Zhang, Zheng Zhang, Webb Miller, and David J. Lipman (1997), &quot;Gapped BLAST and PSI-BLAST: a new generation of protein database search programs&quot;, Nucleic Acids Res. 25:3389-3402.</BlastOutput_reference>
  <BlastOutput_db> /banks/blastPlus/IWGSC_ref_V1_chr1A</BlastOutput_db>
  <BlastOutput_query-ID>Query_1</BlastOutput_query-ID>
  <BlastOutput_query-def>No definition line</BlastOutput_query-def>
  <BlastOutput_query-len>1042</BlastOutput_query-len>
  <BlastOutput_param>
    <Parameters>
      <Parameters_expect>0.0001</Parameters_expect>
      <Parameters_sc-match>2</Parameters_sc-match>
      <Parameters_sc-mismatch>-3</Parameters_sc-mismatch>
      <Parameters_gap-open>5</Parameters_gap-open>
      <Parameters_gap-extend>2</Parameters_gap-extend>
      <Parameters_filter>L;m;</Parameters_filter>
    </Parameters>
  </BlastOutput_param>
<BlastOutput_iterations>
<Iteration>
  <Iteration_iter-num>1</Iteration_iter-num>
  <Iteration_query-ID>Query_1</Iteration_query-ID>
  <Iteration_query-def>No definition line</Iteration_query-def>
  <Iteration_query-len>1042</Iteration_query-len>
<Iteration_hits>
<Hit>
  <Hit_num>1</Hit_num>
  <Hit_id>gnl|IWGSC_ref_V1_chr1A|chr1A</Hit_id>
  <Hit_def>No definition line</Hit_def>
  <Hit_accession>chr1A</Hit_accession>
  <Hit_len>594102056</Hit_len>
  <Hit_hsps>
    <Hsp>
      <Hsp_num>1</Hsp_num>
      <Hsp_bit-score>1880.4</Hsp_bit-score>
      <Hsp_score>2084</Hsp_score>
      <Hsp_evalue>0</Hsp_evalue>
      <Hsp_query-from>1</Hsp_query-from>
      <Hsp_query-to>1042</Hsp_query-to>
      <Hsp_hit-from>1520577</Hsp_hit-from>
      <Hsp_hit-to>1521618</Hsp_hit-to>
      <Hsp_query-frame>1</Hsp_query-frame>
      <Hsp_hit-frame>1</Hsp_hit-frame>
      <Hsp_identity>1042</Hsp_identity>
      <Hsp_positive>1042</Hsp_positive>
      <Hsp_gaps>0</Hsp_gaps>
      <Hsp_align-len>1042</Hsp_align-len>
      <Hsp_qseq>AAGCACATTAGTGCCGGTTTGTATTTGAGCCGGCACTAATGTATACATTAGTGCCGGTTCCAACGGCTAGACGGGCCGCTTTCATTAGTACCGGTTCGTGGCGAACCTTTAGCACCGGTTCGTGCCACGAACCGGTACTAATGAGAGTGGTGGCAGGATGTTGTCAGACTGGGGCCCTCCAGCCCCTTTAGTACCGATTGGTGGCACGAACCGGTACTAAAGGTCGTCCTACATAAACCCTTCACACCCGAGCTCACTCTGTTCTTCCCCTTTCCCCTCTCCTCTCTGTTCTCCCCCTCTTCCTCTCGAGCTCATCACACGTTTTGCCCAAAATTTGTCAAGATTTGAAGGCCCCCATCCATTCAAATGATCACAAAGGTTAGCAACTTTGTCCTTTCATCTCTCATTGCTAGATTATAGCTCTTGCAATGCTTTATATAGTGATTAATTTGTGAGTTTAGTAATTTGGGAGGATATATATATATATATATATATATATATGTGTGTGTGTGTGTGTGTGTGTGTGTGTGTGTGTGTGTGTGCTAGTATTTGATTTATATGCAATTTGAGGTCAAAAATAACACTTAGTTTGCATATGTAGGTGTGGTTTACTTAGTGCCTTCTAAATCTCCTTCGTAACCACCGTCGATCGCCCGCACCGTCCCGTCGCCGGCACCACCTTGTGGTGAGCCTCTTGTTCATGAAATTTTATATAAAAATTGATGTTTGTGTGATTTAGATATATAGTTACTCGTATAATTATCTTACCCGTACGTTGTTTGTTATACATATAGTGCCATGGTTTTGATATCCGTCCCCGTCAGCCCTTGTCCTTGTTATGATTCAGATGTGGTATATATATTCTCTTTTAAAACTAGTTGCATTTCGTGTTTATGACAAATTATGCCCATCAAGTTGACATAGAATTTTTTTCTAGGAGGTATGTGAACCGGAAATTCCAACCGACCCTATTGTCGAGAGGTTAAATTTAGTTGAAAGAGAAAACGAGTACTTGAAAGAAAAATTGAAAAGAATTGAGGGG</Hsp_qseq>
      <Hsp_hseq>AAGCACATTAGTGCCGGTTTGTATTTGAGCCGGCACTAATGTATACATTAGTGCCGGTTCCAACGGCTAGACGGGCCGCTTTCATTAGTACCGGTTCGTGGCGAACCTTTAGCACCGGTTCGTGCCACGAACCGGTACTAATGAGAGTGGTGGCAGGATGTTGTCAGACTGGGGCCCTCCAGCCCCTTTAGTACCGATTGGTGGCACGAACCGGTACTAAAGGTCGTCCTACATAAACCCTTCACACCCGAGCTCACTCTGTTCTTCCCCTTTCCCCTCTCCTCTCTGTTCTCCCCCTCTTCCTCTCGAGCTCATCACACGTTTTGCCCAAAATTTGTCAAGATTTGAAGGCCCCCATCCATTCAAATGATCACAAAGGTTAGCAACTTTGTCCTTTCATCTCTCATTGCTAGATTATAGCTCTTGCAATGCTTTATATAGTGATTAATTTGTGAGTTTAGTAATTTGGGAGGATATATATATATATATATATATATATATGTGTGTGTGTGTGTGTGTGTGTGTGTGTGTGTGTGTGTGTGCTAGTATTTGATTTATATGCAATTTGAGGTCAAAAATAACACTTAGTTTGCATATGTAGGTGTGGTTTACTTAGTGCCTTCTAAATCTCCTTCGTAACCACCGTCGATCGCCCGCACCGTCCCGTCGCCGGCACCACCTTGTGGTGAGCCTCTTGTTCATGAAATTTTATATAAAAATTGATGTTTGTGTGATTTAGATATATAGTTACTCGTATAATTATCTTACCCGTACGTTGTTTGTTATACATATAGTGCCATGGTTTTGATATCCGTCCCCGTCAGCCCTTGTCCTTGTTATGATTCAGATGTGGTATATATATTCTCTTTTAAAACTAGTTGCATTTCGTGTTTATGACAAATTATGCCCATCAAGTTGACATAGAATTTTTTTCTAGGAGGTATGTGAACCGGAAATTCCAACCGACCCTATTGTCGAGAGGTTAAATTTAGTTGAAAGAGAAAACGAGTACTTGAAAGAAAAATTGAAAAGAATTGAGGGG</Hsp_hseq>
      <Hsp_midline>||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||</Hsp_midline>
    </Hsp>
    <Hsp>
      <Hsp_num>2</Hsp_num>
      <Hsp_bit-score>1723.5</Hsp_bit-score>
      <Hsp_score>1910</Hsp_score>
      <Hsp_evalue>0</Hsp_evalue>
      <Hsp_query-from>1</Hsp_query-from>
      <Hsp_query-to>1042</Hsp_query-to>
      <Hsp_hit-from>2774434</Hsp_hit-from>
      <Hsp_hit-to>2775478</Hsp_hit-to>
      <Hsp_query-frame>1</Hsp_query-frame>
      <Hsp_hit-frame>1</Hsp_hit-frame>
      <Hsp_identity>1013</Hsp_identity>
      <Hsp_positive>1013</Hsp_positive>
      <Hsp_gaps>7</Hsp_gaps>
      <Hsp_align-len>1047</Hsp_align-len>
      <Hsp_qseq>AAGCACATTAGTGCCGGTTTGTATTTGAGCCGGCACTAATGTATACATTAGTGCCGGTTCCAACGGCTAGACGGGCCGCTTTCATTAGTACCGGTTCGTGGCGAACCTTTAGCACCGGTTCGTGCCACGAACCGGTACTAATGAGAGTGGTGGCAGGATGTTGTCAGACTGGGGCCC-TCCAGCCCCTTTAGTACCGATTGGTGGCACGAACCGGTACTAAAGGTCGTCCTACATAAACCCTTCA--CACCCGAGCTCACTCTGTTCTTCCCCTTTCCCCTCTCCTCTCTGTTCTCCCCCTCTTCCTCTCGAGCTCATCACACGTTTTGCCCAAAATTTGTCAAGATTTGAAGGCCCCCATCCATTCAAATGATCACAAAGGTTAGCAACTTTGTCCTTTCATCTCTCATTGCTAGATTATAGCTCTTGCAATGCTTTATATAGTGATTAATTTGTGAGTTTAGTAATTTGGGAGG--ATATATATATATATATATATATATATATGTGTGTGTGTGTGTGTGTGTGTGTGTGTGTGTGTGTGTGTGCTAGTATTTGATTTATATGCAATTTGAGGTCAAAAATAACACTTAGTTTGCATATGTAGGTGTGGTTTACTTAGTGCCTTCTAAATCTCCTTCGTAACCACCGTCGATCGCCCGCACCGTCCCGTCGCCGGCACCACCTTGTGGTGAGCCTCTTGTTCATGAAATTTTATATAAAAATTGATGTTTGTGTGATTTAGATATATAGTTACTCGTATAATTATCTTACCCGTACGTTGTTTGTTATACATATAGTGCCATGGTTTTGATATCCGTCCCCGTCAGCCCTTGTCCTTGTTATGATTCAGATGTGGTATATATATTCTCTTTTAAAACTAGTTGCATTTCGTGTTTATGACAAATTATGCCCATCAAGTTGACATAGAATTTTTTTCTAGGAGGTATGTGAACCGGAAATTCCAACCGACCCTATTGTCGAGAGGTTAAATTTAGTTGAAAGAGAAAACGAGTACTTGAAAGAAAAATTGAAAAGAATTGAGGGG</Hsp_qseq>
      <Hsp_hseq>AAGCACATTAGTGCCGGTTTGTATTTGAGCCGGCACTAATGTATACATTAGTGCCGGTTCCAACGGCTAGCCGGGCCGCCTTCATTAGTACCGGTTCGTGGCGAACCTTTAGCACCGGTTCGTGCCACGAACCGGTACTAATGAGAGTGGTGGCAGGATGTTGTCAGAATGGGGCCCCTCCAGCCCCTTTAGTACCGGTTCTTGGCGCGAACCGGTACTAAAGGTCGTCCTACATAAACCCTTCGTCCACCCGAGCTCGCTCTGTTCTTCCCCTTTCCCCTCTCCTCTCTGTTCTTCCCCTCTTCCTCTCGATCTCATCACACATTTTGCCCAAAATTTGTCAAGATTTGAAGGCCCCCATCCATTCAAATGATCACAAAGGTTAGCAACTTTGTCCTTTGATCTCTCATTGCTAGAT--TAGCTCTTGCAATGCTTTATATAGTGATTAATTTGTGAGTTTAGTAATTTGGGAGGATATATATATATATATATATATATATATATATGTGTGTGTGTGTGTGTGTGTGTGTGTGTGTGTGTGTGTGCTAGTATTTGATTTATATGCAATTTGAGGTCAAAAATAACACTTAGTTTGCATATGTAGGTGTGGTTTACTTAGTGCCTTCTAAATCTCCATCGTAGCCACCGTCGATCGCCCGCACCGTCCCGTCGCCGGCACCACCTTGTGGTGAGCCTCTTGTTCGTGAAATTTTATATAAAAATTGATGTTTGTGTGATTTGGATATATAGTTACTCGTATAATTATCTTACCCGTACGCTGTTTGTTATACATATAGTGCCATGGTTTTGATATCCGTCCCCGTCGGCCCTAGTCCTTGTTATGATTCAGATGTGGTATGTATATTCTCTTTTAAAACTAGTTGCATTTTGTGTTTATGACAAATTATGCCCATCAAGTTGACATAGAAATTTTTTCTAGGAGGTATGTGAACCGGAAATTCCAACCGACCCTATTGCCGAGAGGTTAAATTTAGTTGAAAGAGAAAAGGAGTACTTGAAAGAAAAGTTGAAAAGAATTGAGGGG</Hsp_hseq>
      <Hsp_midline>|||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||| |||||||| |||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||| |||||||| ||||||||||||||||||| ||  |||| |||||||||||||||||||||||||||||||||||||   ||||||||||| |||||||||||||||||||||||||||||||||||| |||||||||||||||| |||||||||| |||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||| |||||||||||||||||  ||||||||||||||||||||||||||||||||||||||||||||||||||||||||  |||||||||||||||||||||||||||| |||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||| ||||| ||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||| |||||||||||||||||||||||||||||||||||| ||||||||||||||||||||||||||||||||||||| |||||||||||||||||||||||||||||||||||||||||||||| ||||| ||||||||||||||||||||||||||| ||||||||||||||||||||||||||||| ||||||||||||||||||||||||||||||||||||||| ||||||||||||||||||||||||||||||||||||||||||||||| |||||||||||||||||||||||||||||| ||||||||||||||||| ||||||||||||||||||</Hsp_midline>
    </Hsp>
    <Hsp>
      <Hsp_num>3</Hsp_num>
      <Hsp_bit-score>1669.4</Hsp_bit-score>
      <Hsp_score>1850</Hsp_score>
      <Hsp_evalue>0</Hsp_evalue>
      <Hsp_query-from>2</Hsp_query-from>
      <Hsp_query-to>1042</Hsp_query-to>
      <Hsp_hit-from>582140386</Hsp_hit-from>
      <Hsp_hit-to>582141413</Hsp_hit-to>
      <Hsp_query-frame>1</Hsp_query-frame>
      <Hsp_hit-frame>1</Hsp_hit-frame>
      <Hsp_identity>998</Hsp_identity>
      <Hsp_positive>998</Hsp_positive>
      <Hsp_gaps>23</Hsp_gaps>
      <Hsp_align-len>1046</Hsp_align-len>
      <Hsp_qseq>AGCACATTAGTGCCGGTTTGTATTTGAGCCGGCACTAATGTATACATTAGTGCCGGTTCCAACGGCTAGACGGGCCGCTTTCATTAGTACCGGTTCGTGGCGAACCTTTAGCACCGGTTCGTGCCACGAACCGGTACTAATGAGAGTGGTGGCAGGATGTTGTCAGACTGGGGCCC-TCCAGCCCCTTTAGTACCGATTGGTGGCACGAACCGGTACTAAAGGTCGTCCTACATAAACCCTTCA--CACCCGAGCTCACTCTGTTCTTCCCCTTTCCCCTCTCCTCTCT--GTTCTCCCCCTCTTCCTCTCGAGCTCATCACACGTTTTGCCCAAAATTTGTCAAGATTTGAAGGCCCCCATCCATTCAAATGATCACAAAGGTTAGCAACTTTGTCCTTTCATCTCTCATTGCTAGATTATAGCTCTTGCAATGCTTTATATAGTGATTAATTTGTGAGTTTAGTAATTTGGGAGGATATATATATATATATATATATATATATGTGTGTGTGTGTGTGTGTGTGTGTGTGTGTGTGTGTGTGTGCTAGTATTTGATTTATATGCAATTTGAGGTCAAAAATAACACTTAGTTTGCATATGTAGGTGTGGTTTACTTAGTGCCTTCTAAATCTCCTTCGTAACCACCGTCGATCGCCCGCACCGTCCCGTCGCCGGCACCACCTTGTGGTGAGCCTCTTGTTCATGAAATTTTATATAAAAATTGATGTTTGTGTGATTTAGATATATAGTTACTCGTATAATTATCTTACCCGTACGTTGTTTGTTATACATATAGTGCCATGGTTTTGATATCCGTCCCCGTCAGCCCTTGTCCTTGTTATGATTCAGATGTGGTATATATATTCTCTTTTAAAACTAGTTGCATTTCGTGTTTATGACAAATTATGCCCATCAAGTTGACATAGAATTTTTTTCTAGGAGGTATGTGAACCGGAAATTCCAACCGACCCTATTGTCGAGAGGTTAAATTTAGTTGAAAGAGAAAACGAGTACTTGAAAGAAAAATTGAAAAGAATTGAGGGG</Hsp_qseq>
      <Hsp_hseq>AGCACATTAGTGCCGGTTTGTATTTGAGCCGGCACTAATGTGTACATTAGTGCCGGTTCCAATGGCTAGCCGGGCCGCTTTCATTAGTACCGGTTCGTGGCGAACCTTTAGCACCGGTTTGTGCCACGAACCGGTACTAATGAGAGTGGTGGCAGGATGTTGTCAGACTGGGGCCCCTCCAGCCCCTTTAGTACCGGTTCTTGGCACGAACCGGTACTAAAGGTCGTCCTACATAAACCCTTCGTCCACCCGAGCTCGCTCTGTTCTTCCGCTTTCCCCTCTCCTCTCTCTGTTCTTCCCCTCTTCCTCTCGATCTCATCACACATTTTGCCCAAAAATTGTCAAGATTTGAAGGCCCCCATCCATTCAAATGATCACAAAGGTTAGCAACTTTGTCCTTTCATCTCTCATTGCTAGATTA--GCTCTTGCAATGCTTTATATAGTGATTAATTTGTGAGTTTAGTAATTTGGGAGGATATATATATATATATATATATATATATGTGTGTGTGT----------------GTGTGTGTGTGTGTGCTAGTATTTGATTTATATGCAATTTGAGGTCAAAAATAACACTTAGTTCGCATATGTAGGTGTGGTTTACTTAGTGCCTTCTAAATCTCCGTCGTAACCACCGTCGATCGCCCGCACCGTCCCGTCGCCGGCACCACCTTGTGGTGAGCCTCTTGTTCATGAAATTTTATATAAAAATTGATGTTTGTGTGATTTGGATATATAGTTACTCATATAATTATCTTACCTGTACGTTGTTTGTTATACATATAGTGCCATGGTTTTGATATCCGTCCCCGTCGGCCCTCGTCCTTGTTATGATTCGGATGTGGTATATATATTCTCTTTTAAAACTAGTTGCATTTCGTGTTTATGACAAATTATGCCCATCAAGTTGACATAGAAATTTTTTCTAGGAGGTATGTGAACCGGAAATTCCAACCGACCCTATTGTCGAGAGGTTAAATTTAGTTGAAAAAGAAAACAAGTACTTGAAAGAAAAATTGAAAAGAATTGAGGGG</Hsp_hseq>
      <Hsp_midline>||||||||||||||||||||||||||||||||||||||||| |||||||||||||||||||| |||||| ||||||||||||||||||||||||||||||||||||||||||||||||| |||||||||||||||||||||||||||||||||||||||||||||||||||||||| ||||||||||||||||||| ||  ||||||||||||||||||||||||||||||||||||||||||   ||||||||||| |||||||||||| ||||||||||||||||||  ||||| |||||||||||||||| |||||||||| |||||||||||| |||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||  ||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||                ||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||| ||||||||||||||||||||||||||||||||||||||||| |||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||| ||||||||||||||| ||||||||||||||| |||||||||||||||||||||||||||||||||||||||||||||||||||| ||||| |||||||||||||||| |||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||| ||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||| ||||||| |||||||||||||||||||||||||||||||||||</Hsp_midline>
    </Hsp>
    </Hit_hsps>
</Hit>
</Iteration_hits>
  <Iteration_stat>
    <Statistics>
      <Statistics_db-num>1</Statistics_db-num>
      <Statistics_db-len>594102056</Statistics_db-len>
      <Statistics_hsp-len>31</Statistics_hsp-len>
      <Statistics_eff-space>600637147275</Statistics_eff-space>
      <Statistics_kappa>0.41</Statistics_kappa>
      <Statistics_lambda>0.625</Statistics_lambda>
      <Statistics_entropy>0.78</Statistics_entropy>
    </Statistics>
  </Iteration_stat>
</Iteration>
</BlastOutput_iterations>
</BlastOutput>
"""
    def test_retrieved_hseqs(self):
        parser = XmlParser()
        hseqs = parser.parse(self.xml)
        expected = ['AAGCACATTAGTGCCGGTTTGTATTTGAGCCGGCACTAATGTATACATTAGTGCCGGTTCCAACGGCTAGACGGGCCGCTTTCATTAGTACCGGTTCGTGGCGAACCTTTAGCACCGGTTCGTGCCACGAACCGGTACTAATGAGAGTGGTGGCAGGATGTTGTCAGACTGGGGCCCTCCAGCCCCTTTAGTACCGATTGGTGGCACGAACCGGTACTAAAGGTCGTCCTACATAAACCCTTCACACCCGAGCTCACTCTGTTCTTCCCCTTTCCCCTCTCCTCTCTGTTCTCCCCCTCTTCCTCTCGAGCTCATCACACGTTTTGCCCAAAATTTGTCAAGATTTGAAGGCCCCCATCCATTCAAATGATCACAAAGGTTAGCAACTTTGTCCTTTCATCTCTCATTGCTAGATTATAGCTCTTGCAATGCTTTATATAGTGATTAATTTGTGAGTTTAGTAATTTGGGAGGATATATATATATATATATATATATATATGTGTGTGTGTGTGTGTGTGTGTGTGTGTGTGTGTGTGTGTGCTAGTATTTGATTTATATGCAATTTGAGGTCAAAAATAACACTTAGTTTGCATATGTAGGTGTGGTTTACTTAGTGCCTTCTAAATCTCCTTCGTAACCACCGTCGATCGCCCGCACCGTCCCGTCGCCGGCACCACCTTGTGGTGAGCCTCTTGTTCATGAAATTTTATATAAAAATTGATGTTTGTGTGATTTAGATATATAGTTACTCGTATAATTATCTTACCCGTACGTTGTTTGTTATACATATAGTGCCATGGTTTTGATATCCGTCCCCGTCAGCCCTTGTCCTTGTTATGATTCAGATGTGGTATATATATTCTCTTTTAAAACTAGTTGCATTTCGTGTTTATGACAAATTATGCCCATCAAGTTGACATAGAATTTTTTTCTAGGAGGTATGTGAACCGGAAATTCCAACCGACCCTATTGTCGAGAGGTTAAATTTAGTTGAAAGAGAAAACGAGTACTTGAAAGAAAAATTGAAAAGAATTGAGGGG',
                    'AAGCACATTAGTGCCGGTTTGTATTTGAGCCGGCACTAATGTATACATTAGTGCCGGTTCCAACGGCTAGCCGGGCCGCCTTCATTAGTACCGGTTCGTGGCGAACCTTTAGCACCGGTTCGTGCCACGAACCGGTACTAATGAGAGTGGTGGCAGGATGTTGTCAGAATGGGGCCCCTCCAGCCCCTTTAGTACCGGTTCTTGGCGCGAACCGGTACTAAAGGTCGTCCTACATAAACCCTTCGTCCACCCGAGCTCGCTCTGTTCTTCCCCTTTCCCCTCTCCTCTCTGTTCTTCCCCTCTTCCTCTCGATCTCATCACACATTTTGCCCAAAATTTGTCAAGATTTGAAGGCCCCCATCCATTCAAATGATCACAAAGGTTAGCAACTTTGTCCTTTGATCTCTCATTGCTAGAT--TAGCTCTTGCAATGCTTTATATAGTGATTAATTTGTGAGTTTAGTAATTTGGGAGGATATATATATATATATATATATATATATATATGTGTGTGTGTGTGTGTGTGTGTGTGTGTGTGTGTGTGTGCTAGTATTTGATTTATATGCAATTTGAGGTCAAAAATAACACTTAGTTTGCATATGTAGGTGTGGTTTACTTAGTGCCTTCTAAATCTCCATCGTAGCCACCGTCGATCGCCCGCACCGTCCCGTCGCCGGCACCACCTTGTGGTGAGCCTCTTGTTCGTGAAATTTTATATAAAAATTGATGTTTGTGTGATTTGGATATATAGTTACTCGTATAATTATCTTACCCGTACGCTGTTTGTTATACATATAGTGCCATGGTTTTGATATCCGTCCCCGTCGGCCCTAGTCCTTGTTATGATTCAGATGTGGTATGTATATTCTCTTTTAAAACTAGTTGCATTTTGTGTTTATGACAAATTATGCCCATCAAGTTGACATAGAAATTTTTTCTAGGAGGTATGTGAACCGGAAATTCCAACCGACCCTATTGCCGAGAGGTTAAATTTAGTTGAAAGAGAAAAGGAGTACTTGAAAGAAAAGTTGAAAAGAATTGAGGGG',
                    'AGCACATTAGTGCCGGTTTGTATTTGAGCCGGCACTAATGTGTACATTAGTGCCGGTTCCAATGGCTAGCCGGGCCGCTTTCATTAGTACCGGTTCGTGGCGAACCTTTAGCACCGGTTTGTGCCACGAACCGGTACTAATGAGAGTGGTGGCAGGATGTTGTCAGACTGGGGCCCCTCCAGCCCCTTTAGTACCGGTTCTTGGCACGAACCGGTACTAAAGGTCGTCCTACATAAACCCTTCGTCCACCCGAGCTCGCTCTGTTCTTCCGCTTTCCCCTCTCCTCTCTCTGTTCTTCCCCTCTTCCTCTCGATCTCATCACACATTTTGCCCAAAAATTGTCAAGATTTGAAGGCCCCCATCCATTCAAATGATCACAAAGGTTAGCAACTTTGTCCTTTCATCTCTCATTGCTAGATTA--GCTCTTGCAATGCTTTATATAGTGATTAATTTGTGAGTTTAGTAATTTGGGAGGATATATATATATATATATATATATATATGTGTGTGTGT----------------GTGTGTGTGTGTGTGCTAGTATTTGATTTATATGCAATTTGAGGTCAAAAATAACACTTAGTTCGCATATGTAGGTGTGGTTTACTTAGTGCCTTCTAAATCTCCGTCGTAACCACCGTCGATCGCCCGCACCGTCCCGTCGCCGGCACCACCTTGTGGTGAGCCTCTTGTTCATGAAATTTTATATAAAAATTGATGTTTGTGTGATTTGGATATATAGTTACTCATATAATTATCTTACCTGTACGTTGTTTGTTATACATATAGTGCCATGGTTTTGATATCCGTCCCCGTCGGCCCTCGTCCTTGTTATGATTCGGATGTGGTATATATATTCTCTTTTAAAACTAGTTGCATTTCGTGTTTATGACAAATTATGCCCATCAAGTTGACATAGAAATTTTTTCTAGGAGGTATGTGAACCGGAAATTCCAACCGACCCTATTGTCGAGAGGTTAAATTTAGTTGAAAAAGAAAACAAGTACTTGAAAGAAAAATTGAAAAGAATTGAGGGG']
        self.assertEqual(expected, hseqs)

if __name__ == "__main__":
    unittest.main()
